routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::redirect('/', '/login');

// Auth::routes();
Auth::routes(['register' => false]);

Route::get('/dashboard', 'HomeController@index')->name('dashboard');

Route::group(['prefix' => 'actas', 'middleware' => 'auth'], function () {
    Route::resource('nacimientos', 'BirthController');
    
    Route::resource('matrimonios', 'MarriageController');
    Route::resource('defunciones', 'DeathController');
    
    Route::resource('search', 'SearchController')->only(['index', 'store']);
    Route::post('search/results', 'SearchController@results')->name('search.results');

    Route::get('download/nac/{id}/{format}', 'PdfDownloadController@birthDownload')->name('birth.download');
    Route::get('download/mar/{id}/{format}', 'PdfDownloadController@marriageDownload')->name('marriage.download');
    Route::get('download/dea/{id}/{format}', 'PdfDownloadController@deathDownload')->name('death.download');
});

Route::group(['middleware' => 'auth'], function () {
    Route::view('/sistema', 'about')->name('sistema');
    Route::view('/author', 'author')->name('autor');
});

resources/views/layouts/includes/navbar.blade.php
<div class="br-header">
    <div class="br-header-left">
        
    </div>
    <!-- br-header-left -->
    <div class="br-header-right">
        <nav class="nav">
            <!-- dropdown -->
            <div class="dropdown">
                <a href="#" class="nav-link nav-link-profile" data-toggle="dropdown">
                <span class="logged-name hidden-md-down">{{ Auth::user()->name }}</span>
                <img src="{{ asset('bracket-plus/img/profile.jpg') }}" class="wd-32 rounded-circle" alt="" />
                <span class="square-10 bg-success"></span>
                </a>
                <div class="dropdown-menu dropdown-menu-header wd-250">
                    <div class="tx-center">
                        <a href="#"><img src="{{ asset('bracket-plus/img/profile.jpg') }}" class="wd-80 rounded-circle" alt="" /></a>
                        <h6 class="logged-fullname">{{ Auth::user()->name }}</h6>
                        <p>{{ Auth::user()->email }}</p>
                    </div>
                    <hr>
                    <ul class="list-unstyled user-profile-nav">
                        {{-- <li><a href="#"><i class="icon ion-ios-person"></i> Edit Profile</a></li> --}}
                        {{-- <li><a href="#"><i class="icon ion-ios-gear"></i> Settings</a></li> --}}
                        <li>
                            <a href="{{ route('logout') }}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();"><i class="icon ion-power"></i> Salir</a>

                            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                @csrf
                            </form>
                        </li>
                    </ul>
                </div>
                <!-- dropdown-menu -->
            </div>
            <!-- dropdown -->
        </nav>
    </div>
    <!-- br-header-right -->
</div>
<!-- br-header -->

resources/views/layouts/includes/sidebar.blade.php
<div class="br-sideleft sideleft-scrollbar">
    <label class="sidebar-label pd-x-10 mg-t-25 mg-b-20 tx-info">Dashboard</label>
    <ul class="br-sideleft-menu">
        <li class="br-menu-item">
            <a href="{{ route('dashboard') }}" class="br-menu-link">
            <i class="menu-item-icon icon ion-ios-home-outline tx-24"></i>
            <span class="menu-item-label">Inicio</span>
            </a><!-- br-menu-link -->
        </li>
        <!-- br-menu-item -->
        {{-- <li class="br-menu-item">
            <a href="#" class="br-menu-link with-sub">
                <i class="menu-item-icon icon ion-ios-photos-outline tx-20"></i>
                <span class="menu-item-label">Cards &amp; Widgets</span>
            </a>
            <ul class="br-menu-sub">
                <li class="sub-item"><a href="card-dashboard.html" class="sub-link">Dashboard</a></li>
                <li class="sub-item"><a href="card-social.html" class="sub-link">Blog &amp; Social Media</a></li>
                <li class="sub-item"><a href="card-listing.html" class="sub-link">Shop &amp; Listing</a></li>
            </ul>
        </li> --}}
        <!-- br-menu-link -->
    </ul>
    <label class="sidebar-label pd-x-10 mg-t-25 mg-b-20 tx-info">Actas</label>
    <ul class="br-sideleft-menu">
        <li class="br-menu-item">
            <a href="{{ route('nacimientos.index') }}" class="br-menu-link">
                <i class="menu-item-icon icon ion-document tx-24"></i>
                <span class="menu-item-label">Nacimientos</span>
            </a><!-- br-menu-link -->
        </li>
        <!-- br-menu-item -->
        <li class="br-menu-item">
            <a href="{{ route('matrimonios.index') }}" class="br-menu-link">
                <i class="menu-item-icon icon ion-document tx-24"></i>
                <span class="menu-item-label">Matrimonios</span>
            </a><!-- br-menu-link -->
        </li>
        <!-- br-menu-item -->
        <li class="br-menu-item">
            <a href="{{ route('defunciones.index') }}" class="br-menu-link">
                <i class="menu-item-icon icon ion-document tx-24"></i>
                <span class="menu-item-label">Defunciones</span>
            </a><!-- br-menu-link -->
        </li>
        <!-- br-menu-item -->
    </ul>
    <label class="sidebar-label pd-x-10 mg-t-25 mg-b-20 tx-info">Ayuda y Soporte</label>
    <ul class="br-sideleft-menu">
        <li class="br-menu-item">
            <a href="{{ route('sistema') }}" class="br-menu-link">
            <i class="menu-item-icon icon ion-help-circled tx-24"></i>
            <span class="menu-item-label">Acerca del Sistema</span>
            </a><!-- br-menu-link -->
        </li>
    </ul>
    <!-- br-sideleft-menu -->
    <ul class="br-sideleft-menu">
        <li class="br-menu-item">
            <a href="{{ route('autor') }}" class="br-menu-link">
            <i class="menu-item-icon icon ion-coffee tx-24"></i>
            <span class="menu-item-label">Autor</span>
            </a><!-- br-menu-link -->
        </li>
    </ul>
    <!-- br-sideleft-menu -->
</div>
<!-- br-sideleft -->